### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by a1ad** [2stacks/docker-freeradius#38]
See title.

Anyway i got the following problem.
Freeradius starts until:
```
freeradius-freeradius-1  | including configuration file /etc/raddb/sites-enabled/inner-tunnel
freeradius-freeradius-1  | main {
freeradius-freeradius-1  |  security {
freeradius-freeradius-1  |  	user = "freerad"
freeradius-freeradius-1  |  	group = "freerad"
freeradius-freeradius-1  |  	allow_core_dumps = no
freeradius-freeradius-1  |  }
freeradius-freeradius-1  | 	name = "freeradius"
freeradius-freeradius-1  | 	prefix = "/usr"
freeradius-freeradius-1  | 	localstatedir = "/var"
freeradius-freeradius-1  | 	logdir = "/etc/raddb/log/freeradius"
freeradius-freeradius-1  | 	run_dir = "/var/run/freeradius"
freeradius-freeradius-1  | }
```

And got this DB error:

`freeradius-db-1  | 2022-03-16 10:44:38 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '172.26.0.3' (This connection closed normally without authentication)`

When i exec in the DB container i can access the DB with the credentials entered in the compose file and the sql mod file.

compose file:

```
version: '3.2'

services:
  freeradius:
    image: "2stacks/freeradius"
#    ports:
#      - "1812:1812/udp"
#      - "1813:1813/udp"
    volumes:
      - "./configs/radius:/etc/raddb"
    environment:
      - DB_NAME=radius
      - DB_HOST=db
      - DB_USER=radius
      - DB_PASS=radpass
      - DB_PORT=3306
      - RAD_DEBUG=yes
    networks:
      - default
    depends_on:
      - db
    links:
      - db
    restart: always

  db:
    image: mariadb:latest
    volumes:
      - "./configs/mysql:/var/lib/mysql"
    #ports:
    #  - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_USER=radius
      - MYSQL_PASSWORD=radpass
      - MYSQL_DATABASE=radius
    restart: always
    networks:
      - default
```

My DB is migrated from old non docker install.
