### ISSUE TITLE
Authentication not working after update

### ISSUE THREAD

**Issue by jerheij** [2stacks/docker-freeradius#7]
First of all; thanks for your freeradius container, I've been using it as authentication issue for a while and it has been working great.

Unfortunately after updating from container version 1.3 to latest the authentication doesn't work any more. They all result in failures. I've been using this test as a final test: [link](http://deployingradius.com/scripts/eapol_test/).

With version tag **1.3** it works without issues but with **latest** it results in failures. Do you have any clue what the issue could be? I already compared the versions of freeradius in the container and them seem identical.

I only use a basic docker-compose config and an external database:
```
version: '3.2'

services:
  freeradius:
    container_name: radius
    image: "2stacks/freeradius:latest"
    ports:
      - "<IP>:1812:1812/udp"
    environment:
      - DB_NAME=radius_docker
      - DB_HOST=<db IP>
      - DB_USER=<db_user>
      - DB_PASS=<db_pass>
      - DB_PORT=3306
      - RADIUS_KEY=<random key>
      - RAD_CLIENTS=*
      - RAD_DEBUG=yes
    restart: always
    networks:
      infra:
        ipv4_address: <IP>

networks:
  infra:
    external: true
```
